version: '3.8'

services:
  postgres-db:
    image: postgres:16
    container_name: rules-postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: b@ncoPostgr3SQL
      POSTGRES_DB: foracesso
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rules-service:
    build: .
    container_name: rules-service-app
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      # Conexão com PostgreSQL
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres-db:5432/foracesso
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: b@ncoPostgr3SQL
      
      # Habilita a execução do schema.sql no banco de dados primário (PostgreSQL)
      SPRING_SQL_INIT_MODE: always

      # Conexão com o SQL Server Externo
      SPRING_R2DBC_SQLSERVER_URL: r2dbc:sqlserver://host.docker.internal:1433/Foracesso
      SPRING_R2DBC_SQLSERVER_USERNAME: seu_usuario_sql_server
      SPRING_R2DBC_SQLSERVER_PASSWORD: "sua_senha_sql_server"

volumes:
  postgres_data: